@startuml

!define LIGHTBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

activate main
activate bodyCb
main -> main: sendGoal
bodyCb -> bodyCb: detectHumans
bodyCb -> execMc: start
deactivate bodyCb
activate execMc
execMc --> bodyCb: paused1 = true
activate bodyCb
bodyCb -> bodyCb: trackHumans
execMc -> execMc: initBackOff
execMc --> main: paused2 = true
deactivate execMc
main -> main: cancelGoal
main --> execMc: sendingGoal = false
deactivate main
activate execMc
execMc -> execMc: backOff
execMc --> bodyCb: paused1 = false
execMc --> main: paused2 = false
execMc --> loop: ready_to_continue = true
deactivate execMc
activate loop
bodyCb -> bodyCb: trackHumans
deactivate bodyCb
loop --> bodyCb: ready_to_continue = false
activate bodyCb
bodyCb -> bodyCb: detectHumans
loop -> loop: finalizeLog
loop -> loop: continueGoal
loop --> main: sendingGoal = true
deactivate loop
activate main
@enduml